name: Deploy Backend API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Save SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Verify SSH Key File
      run: ls -l key.pem

    - name: Verify SSH Key Content
      run: |
        head -n 5 key.pem
        tail -n 5 key.pem

    - name: Debug Variables
      run: |
        echo "HOST: ${{ secrets.HOST }}"
        echo "USER: ${{ secrets.USER }}"

    - name: Deploy to VM
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        echo "Stopping existing processes on the server..."
        ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "pm2 stop all || true"
        echo "Copying project files to the server..."
        scp -i key.pem -r . $USER@$HOST:/home/$USER/app
        echo "Installing dependencies and starting the application..."
        ssh -i key.pem $USER@$HOST "cd /home/$USER/app && npm install && sudo pm2 start index.js --name backend-api"
